### ISSUE TITLE
PhotoQt 3.4 fails to start on Linux Mint

### ISSUE THREAD

**Issue by bogiord** [flathub/org.photoqt.PhotoQt#13]
Commit https://github.com/flathub/org.photoqt.PhotoQt/commit/bc5413f207d7ed6a4fcfd32801d710221bf972fb breaks PhotoQt on X11-based distros like Linux Mint.

There's no error message in the GUI; nothing visible happens when you try to start PhotoQt, either from the desktop menu or from a file type association.

Running from the terminal with `flatpak run org.photoqt.PhotoQt` outputs the following error:

```
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.
```

Easily fixed with `sudo flatpak override --socket=x11 org.photoqt.PhotoQt`, but still...

**Comment by luspi** [comment]
Thanks for letting me know! The manifest used to contain both sockets, but sometime between the last update and now this has become invalid syntax, and I didn't think it through when removing the x11 socket. [I switched it to only x11 now](#14 ), it should be live soon.

**Comment by bogiord** [comment]
Thanks for the very quick reply, and in general thanks a lot for PhotoQt - at last a viewer that does (almost :smiley:) everything I need the way I need it.

I've yet to build something for flatpak, so I don't really know how those combinations of permissions work, but wouldn't having only `x11` mess something up when running on wayland? Maybe a combination of `wayland` and `fallback-x11` is what the builder tool is expecting?

Hmmm, I've just tried removing `x11` and adding `fallback-x11` with `sudo flatpak override --socket=fallback-x11 org.photoqt.PhotoQt` and it added both `x11` and `fallback-x11` to `[Context]`, but maybe that's down to the flatpak version on my Linux Mint - `1.12.7`.

Sorry for the ramblings, I'm hoping some of that helps.

**Comment by bogiord** [comment]
Working fine on my side. I removed the local override, updated, and `[Context]` now has `sockets=x11;wayland;pulseaudio;fallback-x11;`.

> I'd be curious to hear what you would like to see in PhotoQt that it can't do yet. I'm always looking for feedback and suggestions 😃

I have a handful of pretty minor feedback items, I'll open separate issues for them. Soon, promise 😁.
