### ISSUE TITLE
outdated version of org.freedesktop.Platform.ffmpeg-full

### ISSUE THREAD

**Issue by sunhasgothishaton** [flathub/org.photoqt.PhotoQt#37]
I updated PhotoQt to 4.7 and it installed org.freedesktop.Platform.ffmpeg-full 22.08 which is EOL

This version was added to org.photoqt.PhotoQt.yml file for the 4.7 release
https://github.com/flathub/org.photoqt.PhotoQt/pull/36/files

**Comment by luspi** [comment]
PhotoQt works with all three, and it was my understanding that the first one listed has the highest priority. It seems like I had it backwards (suggested, for instance, by https://github.com/flatpak/flatpak/issues/5718). I put 24.08 now last and removed 22.08. It should be live later today.

**Comment by sunhasgothishaton** [comment]
Great, thank you.

Interesting to read about the order to list the versions.
