### ISSUE TITLE
System tray icon is missing on Wayland (Waybar)

### ISSUE THREAD

**Issue by tinywrkb** [flathub/org.photoqt.PhotoQt#6]
I'm using Waybar status bar with Sway Wayland compositor and there's no system tray icon.  
Waybar has no [XEMBED](https://specifications.freedesktop.org/systemtray-spec/latest/) proxy so [StatusNotifierItem](https://freedesktop.org/wiki/Specifications/StatusNotifierItem/) should be used.  
Adding `--own-name='org.kde.*'` and `--talk-name=org.kde.StatusNotifierWatcher` overrides solves this issue, and the latter is needed per the protocol spec, even though it works fine without it.

One problem that remains and I still didn't figure out is that the icon itself is defaulting a default/blank icon.  
There's no status icon packaged in `share/icons/hicolor/*/status/`, not to mention an exported one. And also the content of the `IconName` property of the registered `org.kde.StatusNotifierItem-*` interface is a path within the sandbox instead of an icon name (I just used D-Feet to confirm).

**Comment by tinywrkb** [comment]
A hacky solution but I managed to get the status bar to show the icon instead of a blank one.

```
diff --git a/cplusplus/mainhandler.cpp b/cplusplus/mainhandler.cpp
index 3a79bdb8..32f85812 100644
--- a/cplusplus/mainhandler.cpp
+++ b/cplusplus/mainhandler.cpp
@@ -404,7 +404,7 @@ void MainHandler::handleTrayIcon(int val) {
             delete trayIcon;
 
         trayIcon = new QSystemTrayIcon(this);
-        trayIcon->setIcon(QIcon(":/img/icon.png"));
+        trayIcon->setIcon(QIcon::fromTheme("org.photoqt.PhotoQt"));
         trayIcon->setToolTip("PhotoQt " + tr("Image Viewer"));
 
         // A context menu for the tray icon
```

But this uses the app icon and not the status icon, I glanced at the Freedesktop specs ([1](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html), [2](https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html)) and I didn't find how to use the status icon.

**Comment by tinywrkb** [comment]
[Reported to PhotoQT](https://gitlab.com/luspi/photoqt/-/issues/75)

**Comment by hfiguiere** [comment]
isn't there something more restrictive than `--own-name=org.kde.*` that could be used?

**Comment by tinywrkb** [comment]
`--talk-name=org.kde.StatusNotifierWatcher` seems to be enough for registering the `StatusNotifierItem`, but I don't have an icon visible, just a blank icon.  
I haven't had any luck in displaying the icon correctly.  
I'm also seeing the signal `org.kde.StatusNotifierItem.NewIcon` in the dbus traffic, so maybe also add `--talk-nam=org.kde.StatusNotifierItem`

In the past, I had a `org.kde.StatusNotifierItem-<NUM>-<NUM>` on the session bus after `StatusNotifierItem` was registered, so I had to add the `--own-name=org.kde.*`, and this for every `StatusNotifierItem` icon, but not anymore.  
I'm not sure why this behavior changed, maybe [this](https://github.com/Alexays/Waybar/pull/598)?
