### ISSUE TITLE
PhotoQt does not have an icon in the apps menu of KDE Plasma

### ISSUE THREAD

**Issue by glaubersm** [flathub/org.photoqt.PhotoQt#7]
Hi
As we can see in the screenshot below, the icon of PhotoQt is missing from the apps menu of KDE Plasma desktop environment. I have this bug on two distributions: Arch Linux and neon unstable.
The icon appears in the apps menu on Arch Linux if I install PhotoQt from AUR instead of from flathub.

![photoqt](https://user-images.githubusercontent.com/15967631/169523021-515d538c-9aba-4982-9cc5-b4b409f1526b.png)

**Comment by luspi** [comment]
Hi @glaubersm 

Thanks for letting me know! I just pushed an update that should fix that. It's currently building here, and should get updated in flathub later today.

**Comment by glaubersm** [comment]
it's fixed now. Thank you.
